[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
favorites = "GfwhbDPReQUpdUK6ikBbM9AzkrCE1uVb2dKvr6rqVJQW"
# favorites = "3kRooyh7ZsWYVwHr5Y4sfHcGKLaEDQg4zmvV2PYjzjbp"

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "localnet"
cluster = "https://api.devnet.solana.com"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run jest --preset ts-jest --detectOpenHandles"
